name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    concurrency:
      cancel-in-progress: true
      group: ${{ github.workflow }}-${{ github.ref }}
    permissions:
      contents: write
    timeout-minutes: 5
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version-file: package.json

      - name: 🪶 Update changelog
        run: npx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
